### PR TITLE
Support mkdocs v1.1

### PR DESCRIPTION
**Pull request by janaz**
The latest version of `mkdocs` dropped Python2 support and they removed the `string_types` alias to either `str` (v3) or `basestring` (v2)

### CODE REVIEW

**Comment by janaz** [comment]
After upgrading `mkdocs` to v1.1 the following error is thrown:

```
  File "/usr/local/lib/python3.7/site-packages/plugin/plugin.py", line 9, in UserDefinedValues
    ('input-placeholder', config_options.Type(mkdocs_utils.string_types, default='{{{user-defined-values}}}'))
AttributeError: module 'mkdocs.utils' has no attribute 'string_types'```
